# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.darts_match_pb2 as darts__match__pb2


class DartsMatchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVisit = channel.unary_unary(
                '/app.DartsMatch/ProcessVisit',
                request_serializer=darts__match__pb2.VisitRequest.SerializeToString,
                response_deserializer=darts__match__pb2.VisitResponse.FromString,
                )


class DartsMatchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessVisit(self, request, context):
        """rpc CreateMatch (MatchRequest) return (MatchResponse) {}
        rpc RegisterPlayer (RegisterRequest) returns (RegisterResponse) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DartsMatchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVisit': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessVisit,
                    request_deserializer=darts__match__pb2.VisitRequest.FromString,
                    response_serializer=darts__match__pb2.VisitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.DartsMatch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DartsMatch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessVisit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.DartsMatch/ProcessVisit',
            darts__match__pb2.VisitRequest.SerializeToString,
            darts__match__pb2.VisitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
