# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.visit_pb2 as visit__pb2


class VisitStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVisit = channel.unary_unary(
                '/app.Visit/ProcessVisit',
                request_serializer=visit__pb2.VisitRequest.SerializeToString,
                response_deserializer=visit__pb2.VisitResponse.FromString,
                )


class VisitServicer(object):
    """The greeting service definition.
    """

    def ProcessVisit(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVisit': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessVisit,
                    request_deserializer=visit__pb2.VisitRequest.FromString,
                    response_serializer=visit__pb2.VisitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.Visit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Visit(object):
    """The greeting service definition.
    """

    @staticmethod
    def ProcessVisit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.Visit/ProcessVisit',
            visit__pb2.VisitRequest.SerializeToString,
            visit__pb2.VisitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
