# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visit.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='visit.proto',
  package='app',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bvisit.proto\x12\x03\x61pp\"7\n\x0cVisitRequest\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x18\n\x05visit\x18\x02 \x03(\x0b\x32\t.app.Dart\"\x85\x01\n\x04\x44\x61rt\x12,\n\nmultiplier\x18\x01 \x01(\x0e\x32\x18.app.Dart.DartMultiplier\x12\x0f\n\x07segment\x18\x02 \x01(\x05\">\n\x0e\x44\x61rtMultiplier\x12\x08\n\x04MISS\x10\x00\x12\n\n\x06SINGLE\x10\x01\x12\n\n\x06\x44OUBLE\x10\x02\x12\n\n\x06TREBLE\x10\x03\"0\n\rVisitResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2@\n\x05Visit\x12\x37\n\x0cProcessVisit\x12\x11.app.VisitRequest\x1a\x12.app.VisitResponse\"\x00\x62\x06proto3'
)



_DART_DARTMULTIPLIER = _descriptor.EnumDescriptor(
  name='DartMultiplier',
  full_name='app.Dart.DartMultiplier',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MISS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SINGLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TREBLE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=149,
  serialized_end=211,
)
_sym_db.RegisterEnumDescriptor(_DART_DARTMULTIPLIER)


_VISITREQUEST = _descriptor.Descriptor(
  name='VisitRequest',
  full_name='app.VisitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='app.VisitRequest.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visit', full_name='app.VisitRequest.visit', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=75,
)


_DART = _descriptor.Descriptor(
  name='Dart',
  full_name='app.Dart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='app.Dart.multiplier', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segment', full_name='app.Dart.segment', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DART_DARTMULTIPLIER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=211,
)


_VISITRESPONSE = _descriptor.Descriptor(
  name='VisitResponse',
  full_name='app.VisitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='app.VisitResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='app.VisitResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=261,
)

_VISITREQUEST.fields_by_name['visit'].message_type = _DART
_DART.fields_by_name['multiplier'].enum_type = _DART_DARTMULTIPLIER
_DART_DARTMULTIPLIER.containing_type = _DART
DESCRIPTOR.message_types_by_name['VisitRequest'] = _VISITREQUEST
DESCRIPTOR.message_types_by_name['Dart'] = _DART
DESCRIPTOR.message_types_by_name['VisitResponse'] = _VISITRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisitRequest = _reflection.GeneratedProtocolMessageType('VisitRequest', (_message.Message,), {
  'DESCRIPTOR' : _VISITREQUEST,
  '__module__' : 'visit_pb2'
  # @@protoc_insertion_point(class_scope:app.VisitRequest)
  })
_sym_db.RegisterMessage(VisitRequest)

Dart = _reflection.GeneratedProtocolMessageType('Dart', (_message.Message,), {
  'DESCRIPTOR' : _DART,
  '__module__' : 'visit_pb2'
  # @@protoc_insertion_point(class_scope:app.Dart)
  })
_sym_db.RegisterMessage(Dart)

VisitResponse = _reflection.GeneratedProtocolMessageType('VisitResponse', (_message.Message,), {
  'DESCRIPTOR' : _VISITRESPONSE,
  '__module__' : 'visit_pb2'
  # @@protoc_insertion_point(class_scope:app.VisitResponse)
  })
_sym_db.RegisterMessage(VisitResponse)



_VISIT = _descriptor.ServiceDescriptor(
  name='Visit',
  full_name='app.Visit',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=263,
  serialized_end=327,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessVisit',
    full_name='app.Visit.ProcessVisit',
    index=0,
    containing_service=None,
    input_type=_VISITREQUEST,
    output_type=_VISITRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VISIT)

DESCRIPTOR.services_by_name['Visit'] = _VISIT

# @@protoc_insertion_point(module_scope)
